module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

  mounts:
  - source: assets
    target: assets
  - source: layouts
    target: layouts
  - source: static
    target: static
  - source: content
    target: content
