baseURL = "/"
languageCode = "en-us"
title = "Stack Moments - Daily"
theme = "PaperMod"

[pagination]
pagerSize = 12
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = ""

minify = true

[params]
  env = "production"
  title = "Stack Moments - Daily"
  description = "Daily tech news, insights, and deep research for developers and tech professionals"
  keywords = ["tech news", "programming", "development", "software", "AI", "technology"]
  author = "Stack Moments Team"
  images = ["cover.png"]
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  comments = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.homeInfoParams]
    Title = "Welcome to Stack Moments - Daily"
    Content = "Your daily dose of tech news, programming insights, and deep research content for developers and technology professionals."

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/"

  [params.analytics.google]
    SiteVerificationTag = ""

  [params.cover]
    hidden = true
    hiddenInList = true
    hiddenInSingle = true

  [params.editPost]
    URL = "https://github.com/yourusername/stack-moments-daily/tree/main/content"
    Text = "Suggest Changes"
    appendFilePath = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

  # Giscus Comments Configuration
  [params.giscus]
    repo = ""
    repoId = ""
    category = ""
    categoryId = ""
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "en"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Articles"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "briefs"
    name = "News Briefs"
    url = "/briefs/"
    weight = 30

  [[menu.main]]
    identifier = "topics"
    name = "Topics"
    url = "/topics/"
    weight = 40

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 50

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 60

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    style = "github"
    hl_inline = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.x]
    disableInlineCSS = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
